version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: player_analytics_db
    environment:
      POSTGRES_DB: player_analytics
      POSTGRES_USER: analytics_user
      POSTGRES_PASSWORD: analytics_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U analytics_user -d player_analytics"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: